### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by UseMuse** [TarikHuber/react-most-wanted#105]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (D:\repos\my-app\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\repos\my-app\node_modules\express\lib\router\index.js:317:13)
    at D:\repos\my-app\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\repos\my-app\node_modules\express\lib\router\index.js:335:12)
    at next (D:\repos\my-app\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\repos\my-app\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\repos\my-app\node_modules\express\lib\router\index.js:317:13)
    at D:\repos\my-app\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\repos\my-app\node_modules\express\lib\router\index.js:335:12)
    at next (D:\repos\my-app\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\repos\my-app\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)

**Comment by TarikHuber** [comment]
Can you pls give us some more context?

**Comment by UseMuse** [comment]
@TarikHuber 
I want to start a project, follow these instructions:

I like short README's so here we go 😎

How to start?
Just run this command:

npx create-react-app my-app --template rmw
cd my-app
npm start
If you are using this npx command make sure to uninstall create-react-app on your device to have the newest version. To do so run:

npm uninstall create-react-app

...
getting this error

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
> at validateString (internal/validators.js:112:11)
> at Object.join (path.js:375:7)
> at noopServiceWorkerMiddleware (D:\repos\my-app\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
> at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)
> at trim_prefix (D:\repos\my-app\node_modules\express\lib\router\index.js:317:13)
> at D:\repos\my-app\node_modules\express\lib\router\index.js:284:7
> at Function.process_params (D:\repos\my-app\node_modules\express\lib\router\index.js:335:12)
> at next (D:\repos\my-app\node_modules\express\lib\router\index.js:275:10)
> at launchEditorMiddleware (D:\repos\my-app\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
> at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)
> at trim_prefix (D:\repos\my-app\node_modules\express\lib\router\index.js:317:13)
> at D:\repos\my-app\node_modules\express\lib\router\index.js:284:7
> at Function.process_params (D:\repos\my-app\node_modules\express\lib\router\index.js:335:12)
> at next (D:\repos\my-app\node_modules\express\lib\router\index.js:275:10)
> at handleWebpackInternalMiddleware (D:\repos\my-app\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
> at Layer.handle [as handle_request] (D:\repos\my-app\node_modules\express\lib\router\layer.js:95:5)

**Comment by TarikHuber** [comment]
I think it is related to this issue: https://github.com/facebook/create-react-app/issues/8499

**Comment by UseMuse** [comment]
it turns out following your instructions for launching the project, this error is caught, I wanted to say this

**Comment by SandruSebastian** [comment]
@TarikHuber I am having this too

**Comment by UseMuse** [comment]
@SandruSebastian in which file can you specify the path to the file?

**Comment by pavlobu** [comment]
[i had been down this path too](https://github.com/TarikHuber/react-most-wanted/issues/117#issuecomment-614830428)
