### ISSUE TITLE
Problem creating an app with windows powershell

### ISSUE THREAD

**Issue by fn2505** [TarikHuber/react-most-wanted#46]
I wanted to try creating an app. But my ignorance did not allow me. I used windows powershell on windows 10. I don't understand where I'm wrong. Anyway, sorry for my bad English.
```
`PS C:\Users\Tommaso\Desktop> npx create-react-app test-app --scripts-version rmw-react-scripts
npx: installed 63 in 19.661s

Creating a new React app in C:\Users\Tommaso\Desktop\test-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and rmw-react-scripts...

+ react-dom@16.8.5
+ react@16.8.5
+ rmw-react-scripts@2.0.19
added 1901 packages from 665 contributors and audited 32603 packages in 533.539s
found 64 vulnerabilities (63 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installing template dependencies using npm...

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer

> grpc@1.19.0 install C:\Users\Tommaso\Desktop\test-app\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\Tommaso\Desktop\test-app\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown\grpc_node.node" is installed via remote

> jss@9.8.7 postinstall C:\Users\Tommaso\Desktop\test-app\node_modules\jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate
npm WARN fireform@0.2.13 requires a peer of firebase@4.x but none is installed. You must install peer dependencies yourself.
npm WARN fireform@0.2.13 requires a peer of redux-form@7.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of firekit-provider@0.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of material-ui-image@3.0.0-pre.7 but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of react-mic@9.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of redux-form-material-ui@5.0.0-beta.2 but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of redux-logger@3.x but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of redux-form@7 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of @material-ui/core@1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ chart.js@2.8.0
+ downshift@3.2.7
+ a2hs@1.0.2
+ @material-ui/icons@3.0.2
+ firebaseui@3.5.2
+ fireform@0.2.13
+ firekit@1.0.30
+ @material-ui/core@3.9.2
+ firekit-provider@1.0.1
+ github-markdown-css@2.10.0
+ firebase@5.9.1
+ prop-types@15.7.2
+ moment@2.24.0
+ material-ui-pickers@2.2.4
+ @date-io/moment@0.0.2
+ react@16.8.5
+ react-chartjs-2@2.7.4
+ intl@1.2.5
+ react-dom@16.8.5
+ material-ui-filter@2.1.14
+ intl-locales-supported@1.0.0
+ react-helmet@5.2.0
+ match-sorter@2.3.0
+ material-ui-image@3.1.0
+ react-countup@4.1.1
+ react-intl@2.8.0
+ react-custom-scrollbars@4.2.1
+ muishift@1.0.13
+ react-image-cropper@1.3.0
+ react-list@0.8.11
+ react-loadable@5.5.0
+ react-mic@12.4.1
+ react-markdown@4.0.6
+ react-router@4.3.1
+ react-player@1.10.0
+ react-redux@6.0.1
+ react-router-dom@4.3.1
+ react-toastify@4.5.2
+ redux@4.0.1
+ react-virtualized@9.21.0
+ redux-persist@5.10.0
+ redux-thunk@2.3.0
+ redux-form@8.1.0
+ rmw-shell@5.0.25
+ redux-form-material-ui@5.0.0-beta.3
added 387 packages from 406 contributors, updated 3 packages and audited 34956 packages in 405.689s
found 97 vulnerabilities (64 low, 32 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installing dev template dependencies using npm...

npm WARN fireform@0.2.13 requires a peer of firebase@4.x but none is installed. You must install peer dependencies yourself.
npm WARN fireform@0.2.13 requires a peer of redux-form@7.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-filter@2.1.14 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN muishift@1.0.13 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of redux-form@7 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@5.0.0-beta.3 requires a peer of @material-ui/core@1 but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of @material-ui/core@1.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of @material-ui/icons@1.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of downshift@2.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of firekit-provider@0.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of material-ui-image@3.0.0-pre.7 but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of react-mic@9.x but none is installed. You must install peer dependencies yourself.
npm WARN rmw-shell@5.0.25 requires a peer of redux-form-material-ui@5.0.0-beta.2 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ redux-logger@3.0.6
+ selenium-webdriver@4.0.0-alpha.1
+ react-scripts@2.1.8
added 273 packages from 307 contributors and audited 71207 packages in 148.541s
found 160 vulnerabilities (127 low, 32 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Success! Created test-app at C:\Users\Tommaso\Desktop\test-app
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd test-app
  npm start

Happy hacking!
PS C:\Users\Tommaso\Desktop> npm start
npm ERR! path C:\Users\Tommaso\Desktop\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Tommaso\Desktop\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tommaso\AppData\Roaming\npm-cache\_logs\2019-03-25T08_38_29_597Z-debug.log`

[2019-03-25T08_38_29_597Z-debug.log](https://github.com/TarikHuber/react-most-wanted/files/3002346/2019-03-25T08_38_29_597Z-debug.log)
```

**Comment by TarikHuber** [comment]
Hi @fn2505 ,

Can you take a look into this treath. Maybe it can help:
https://github.com/TarikHuber/react-most-wanted/issues/37

#37

**Comment by fn2505** [comment]
Thanks for the fast reply. I forgot to mention, that I didn't install it before creating the app. Are there any essential requirements?

**Comment by TarikHuber** [comment]
Everything should workout just with that first command but some CLIs and OS can make problems and you have to fix small stuff on your own. In most cases there are just some little libs making problems. You can also tra to go into the project and delete 'node_modules" and 'package-lock.json" and run 'npm i' to get a fresh installation of all packages.

**Comment by fn2505** [comment]
I tried to follow the various soul, I just can't. But I'm sure the problem is me. I will try calmly in the future

**Comment by TarikHuber** [comment]
@fn2505 we are here to help. Try also to find help here: https://gitter.im/react-most-wanted/Lobby

And let us know if the error messages change. And yes you CAN do this!

**Comment by fn2505** [comment]
error final step "firebase deploy"
```
C:\Users\Tommaso\Desktop\test-app>firebase deploy

=== Deploying to 'test-prod'...

i  deploying database, storage, firestore, functions, hosting
Running command: npm --prefix ./functions run lint

> functions@ lint C:\Users\Tommaso\Desktop\test-app\functions
> eslint .

"eslint" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tommaso\AppData\Roaming\npm-cache\_logs\2019-05-15T10_50_10_127Z-debug.log
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix .\functions run lint ENOENT
    at notFoundError (C:\Users\Tommaso\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Tommaso\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Tommaso\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\Tommaso\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)

Error: functions predeploy error: Command terminated with non-zero exit code1
```
